/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: unitree_go.h
  Source: unitree_go.idl
  Cyclone DDS: V0.8.2

*****************************************************************/
#ifndef DDSC_UNITREE_GO_H
#define DDSC_UNITREE_GO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct unitree_go_msg_dds__IMUState_
{
  float quaternion[4];
  float gyroscope[3];
  float accelerometer[3];
  float rpy[3];
  uint8_t temperature;
} unitree_go_msg_dds__IMUState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__IMUState__desc;

#define unitree_go_msg_dds__IMUState___alloc() \
((unitree_go_msg_dds__IMUState_*) dds_alloc (sizeof (unitree_go_msg_dds__IMUState_)));

#define unitree_go_msg_dds__IMUState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__IMUState__desc, (o))

typedef struct unitree_go_msg_dds__MotorState_
{
  uint8_t mode;
  float q;
  float dq;
  float ddq;
  float tau_est;
  float q_raw;
  float dq_raw;
  float ddq_raw;
  uint8_t temperature;
  uint32_t lost;
  uint32_t reserve[2];
} unitree_go_msg_dds__MotorState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__MotorState__desc;

#define unitree_go_msg_dds__MotorState___alloc() \
((unitree_go_msg_dds__MotorState_*) dds_alloc (sizeof (unitree_go_msg_dds__MotorState_)));

#define unitree_go_msg_dds__MotorState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__MotorState__desc, (o))

typedef struct unitree_go_msg_dds__BmsState_
{
  uint8_t version_high;
  uint8_t version_low;
  uint8_t status;
  uint8_t soc;
  int32_t current;
  uint16_t cycle;
  uint8_t bq_ntc[2];
  uint8_t mcu_ntc[2];
  uint16_t cell_vol[15];
} unitree_go_msg_dds__BmsState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__BmsState__desc;

#define unitree_go_msg_dds__BmsState___alloc() \
((unitree_go_msg_dds__BmsState_*) dds_alloc (sizeof (unitree_go_msg_dds__BmsState_)));

#define unitree_go_msg_dds__BmsState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__BmsState__desc, (o))

typedef struct unitree_go_msg_dds__LowState_
{
  uint8_t head[2];
  uint8_t level_flag;
  uint8_t frame_reserve;
  uint32_t sn[2];
  uint32_t version[2];
  uint16_t bandwidth;
  unitree_go_msg_dds__IMUState_ imu_state;
  unitree_go_msg_dds__MotorState_ motor_state[20];
  unitree_go_msg_dds__BmsState_ bms_state;
  int16_t foot_force[4];
  int16_t foot_force_est[4];
  uint32_t tick;
  uint8_t wireless_remote[40];
  uint8_t bit_flag;
  float adc_reel;
  uint8_t temperature_ntc1;
  uint8_t temperature_ntc2;
  float power_v;
  float power_a;
  uint16_t fan_frequency[4];
  uint32_t reserve;
  uint32_t crc;
} unitree_go_msg_dds__LowState_;

extern const dds_topic_descriptor_t unitree_go_msg_dds__LowState__desc;

#define unitree_go_msg_dds__LowState___alloc() \
((unitree_go_msg_dds__LowState_*) dds_alloc (sizeof (unitree_go_msg_dds__LowState_)));

#define unitree_go_msg_dds__LowState__free(d,o) \
dds_sample_free ((d), &unitree_go_msg_dds__LowState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_UNITREE_GO_H */
