/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: unitree_go.c
  Source: unitree_go.idl
  Cyclone DDS: V0.8.2

*****************************************************************/
#include "unitree_go.h"

static const uint32_t unitree_go_msg_dds__IMUState__ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__IMUState_, quaternion), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__IMUState_, gyroscope), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__IMUState_, accelerometer), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__IMUState_, rpy), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__IMUState_, temperature),
  DDS_OP_RTS
};

const dds_topic_descriptor_t unitree_go_msg_dds__IMUState__desc =
{
  sizeof (unitree_go_msg_dds__IMUState_),
  4u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "unitree_go::msg::dds_::IMUState_",
  NULL,
  6,
  unitree_go_msg_dds__IMUState__ops,
  ""
};
static const uint32_t unitree_go_msg_dds__MotorState__ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__MotorState_, mode),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, q),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, dq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, ddq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, tau_est),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, q_raw),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, dq_raw),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, ddq_raw),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__MotorState_, temperature),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (unitree_go_msg_dds__MotorState_, lost),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY, offsetof (unitree_go_msg_dds__MotorState_, reserve), 2u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t unitree_go_msg_dds__MotorState__desc =
{
  sizeof (unitree_go_msg_dds__MotorState_),
  4u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "unitree_go::msg::dds_::MotorState_",
  NULL,
  12,
  unitree_go_msg_dds__MotorState__ops,
  ""
};
static const uint32_t unitree_go_msg_dds__BmsState__ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__BmsState_, version_high),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__BmsState_, version_low),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__BmsState_, status),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__BmsState_, soc),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (unitree_go_msg_dds__BmsState_, current),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (unitree_go_msg_dds__BmsState_, cycle),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (unitree_go_msg_dds__BmsState_, bq_ntc), 2u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (unitree_go_msg_dds__BmsState_, mcu_ntc), 2u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY, offsetof (unitree_go_msg_dds__BmsState_, cell_vol), 15u,
  DDS_OP_RTS
};

const dds_topic_descriptor_t unitree_go_msg_dds__BmsState__desc =
{
  sizeof (unitree_go_msg_dds__BmsState_),
  4u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "unitree_go::msg::dds_::BmsState_",
  NULL,
  10,
  unitree_go_msg_dds__BmsState__ops,
  ""
};
static const uint32_t unitree_go_msg_dds__LowState__ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, head), 2u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, level_flag),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, frame_reserve),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY, offsetof (unitree_go_msg_dds__LowState_, sn), 2u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY, offsetof (unitree_go_msg_dds__LowState_, version), 2u,
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (unitree_go_msg_dds__LowState_, bandwidth),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__LowState_, imu_state.quaternion), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__LowState_, imu_state.gyroscope), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__LowState_, imu_state.accelerometer), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__LowState_, imu_state.rpy), 3u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, imu_state.temperature),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_STU, offsetof (unitree_go_msg_dds__LowState_, motor_state), 20u,
  (29u << 16u) + 5u, sizeof (unitree_go_msg_dds__MotorState_),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__MotorState_, mode),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, q),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, dq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, ddq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, tau_est),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, q_raw),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, dq_raw),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__MotorState_, ddq_raw),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__MotorState_, temperature),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (unitree_go_msg_dds__MotorState_, lost),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_4BY, offsetof (unitree_go_msg_dds__MotorState_, reserve), 2u,
  DDS_OP_RTS,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.version_high),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.version_low),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.status),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.soc),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (unitree_go_msg_dds__LowState_, bms_state.current),
  DDS_OP_ADR | DDS_OP_TYPE_2BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.cycle),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.bq_ntc), 2u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.mcu_ntc), 2u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY, offsetof (unitree_go_msg_dds__LowState_, bms_state.cell_vol), 15u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY | DDS_OP_FLAG_SGN, offsetof (unitree_go_msg_dds__LowState_, foot_force), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY | DDS_OP_FLAG_SGN, offsetof (unitree_go_msg_dds__LowState_, foot_force_est), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (unitree_go_msg_dds__LowState_, tick),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, wireless_remote), 40u,
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, bit_flag),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__LowState_, adc_reel),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, temperature_ntc1),
  DDS_OP_ADR | DDS_OP_TYPE_1BY, offsetof (unitree_go_msg_dds__LowState_, temperature_ntc2),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__LowState_, power_v),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_FP, offsetof (unitree_go_msg_dds__LowState_, power_a),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_2BY, offsetof (unitree_go_msg_dds__LowState_, fan_frequency), 4u,
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (unitree_go_msg_dds__LowState_, reserve),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (unitree_go_msg_dds__LowState_, crc),
  DDS_OP_RTS
};

const dds_topic_descriptor_t unitree_go_msg_dds__LowState__desc =
{
  sizeof (unitree_go_msg_dds__LowState_),
  4u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "unitree_go::msg::dds_::LowState_",
  NULL,
  47,
  unitree_go_msg_dds__LowState__ops,
  ""
};
